# Generated by Django 3.2.7 on 2021-10-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学校'),
        ),
    ]
