# Generated by Django 3.2.7 on 2021-10-23 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'depth__lt': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='timeline.category', verbose_name='親カテゴリー'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=timeline.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='timeline.category'),
        ),
    ]
