# Generated by Django 3.2.7 on 2021-10-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recruitment_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='募集条件'),
        ),
    ]
