# Generated by Django 3.2.7 on 2021-10-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recruitment_conditions',
        ),
        migrations.AddField(
            model_name='category',
            name='default_img',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/', verbose_name='デフォルト画像'),
        ),
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.IntegerField(default=0, help_text='先祖の数を手動で入力してください', verbose_name='世代'),
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='応募期限'),
        ),
        migrations.AddField(
            model_name='post',
            name='restriction',
            field=models.TextField(blank=True, null=True, verbose_name='応募条件'),
        ),
        migrations.AddField(
            model_name='post',
            name='state_control_type',
            field=models.CharField(choices=[('auto', '自動的に更新'), ('open', '強制的にオープン'), ('close', '強制的にクローズ')], default='auto', max_length=10, verbose_name='募集ステータス'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'depth__lt': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.category', verbose_name='親カテゴリー'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timeline.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
    ]
