# Generated by Django 3.2.7 on 2021-10-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
