# Generated by Django 3.2.7 on 2021-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20211023_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='restriction',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='応募条件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
