# Generated by Django 3.2.7 on 2021-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20210925_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/', verbose_name='写真'),
        ),
    ]
