# Generated by Django 3.2.7 on 2021-10-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20211018_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state_control_type',
        ),
    ]
