# Generated by Django 3.2.7 on 2021-10-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20211017_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'depth__lt': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.category', verbose_name='親カテゴリー'),
        ),
    ]
