# Generated by Django 3.2.7 on 2021-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20210929_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recruited',
            field=models.BooleanField(default=True, verbose_name='募集中'),
        ),
    ]
