# Generated by Django 3.2.7 on 2021-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_category_default_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='depth',
            field=models.IntegerField(default=0, help_text='先祖の数を手動で入力してください', verbose_name='世代'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
    ]
