# Generated by Django 3.2.7 on 2021-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recruitment_conditions',
        ),
        migrations.AddField(
            model_name='post',
            name='restriction',
            field=models.TextField(blank=True, null=True, verbose_name='応募条件'),
        ),
    ]
