# Generated by Django 3.2.7 on 2021-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20211018_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state_judgement_type',
            field=models.IntegerField(choices=[(1, '自動更新'), (2, '強制的にオープン'), (3, '強制的にクローズ')], default=1),
        ),
    ]
