# Generated by Django 3.2.7 on 2021-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_post_state_judgement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state_judgement_type',
            field=models.IntegerField(choices=[(1, '自動的に更新'), (2, '強制的にオープン'), (3, '強制的にクローズ')], default=1, verbose_name='募集状態'),
        ),
    ]
