# Generated by Django 3.2.7 on 2021-10-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_alter_post_state_judgement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='state_judgement_type',
            new_name='state_control_type',
        ),
    ]
