# Generated by Django 3.2.7 on 2021-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_rename_state_judgement_type_post_state_control_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state_control_type',
            field=models.CharField(choices=[('auto', '自動的に更新'), ('open', '強制的にオープン'), ('close', '強制的にクローズ')], default='auto', max_length=10, verbose_name='募集ステータス'),
        ),
    ]
