# Generated by Django 3.2.7 on 2021-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_alter_messagemodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
